genai_solutions:
  supply_chain: "AI-powered demand forecasting and logistics optimization models."
  predictive_maintenance: "Machine learning for predictive maintenance using sensor data analysis."
  workforce_training: "Personalized training bots and real-time support with NLP."
