# Agent-specific settings

industry_research_agent:
  timeout: 30                     # Timeout in seconds for data retrieval
  max_results: 10
  data_sources:
    - "https://api.example.com/industry"
    - "https://api.example.com/company"

use_case_generation_agent:
  max_use_cases: 5
  trends_analysis_enabled: true   # Enable analysis of industry trends
  focus_areas:
    - "Supply Chain Optimization"
    - "Predictive Maintenance"
    - "Workforce Training and Support"

resource_asset_collection_agent:
  dataset_sources:
    - "https://www.kaggle.com"
    - "https://huggingface.co"
    - "https://github.com"
  max_datasets_per_use_case: 3
  timeout: 20

genai_solution_agent:
  enable_suggestions: true
  suggestion_type: "NLP, ML"  
  
use_case_defaults:
  - "Supply Chain Optimization"
  - "Predictive Maintenance"
  - "Workforce Training"
genai_solutions:
  - "Document Search"
  - "Automated Report Generation"
  - "AI Chatbot for Customer Support"
